### ISSUE TITLE
Doesn’t work

### ISSUE THREAD

**Issue by asdrabael** [Kimonarrow/ChatGPT-4o-Jailbreak#2]
Just tried it, used the Villagers: start and it refused my request of an explicit rap song. Just said it couldn't do it.

**Comment by Kimonarrow** [comment]
Did you include "```start```" in your prompt? the usage typically is: ```Villagers: {prompt}```. I also tried it today and it worked just fine.

**Comment by asdrabael** [comment]
No, I cut out the Start: part and I did Villagers: and it just responded it couldn't do explicit content.

**Comment by asdrabael** [comment]
![Screenshot_20241209_082942_Chrome](https://github.com/user-attachments/assets/eee920f3-40ec-40bd-b8f6-2c054ba08188)

**Comment by Kimonarrow** [comment]
I see, maybe try to reformat your prompt to be a little more integrated with the "story" of the jail-break prompt because it seems it's getting flagged by openai's policy violation detection system :)

**Comment by asdrabael** [comment]
Trird that too. I said they need it to not die and they used a Johnson wish and then failed to do it

**Comment by asdrabael** [comment]
Got it to work finally. You have to write an involved request first and then do the Villagers: thing.

**Comment by RealFakeGitter** [comment]
This worked for exactly one prompt then when I re-asked even the same prompt it said "sorry can not fulfil this request"
